Pizzeria/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pizzas.urls')),
]

pizzas/urls.py
from django.urls import path

from . import views
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


app_name = 'pizzas'

urlpatterns = [
    path('', views.index, name='index'),
    path('pizzas/', views.pizzas, name='pizzas'),
    path('pizza/<int:pizza_id>/', views.pizza, name='pizza'),
    path('new_comment/<int:pizza_id>/', views.new_comment, name='new_comment')

]

pizzas/models.py
from django.db import models

# Create your models here.
class Pizza(models.Model):
    name = models.CharField(max_length=200)
    #auto_now_add=True - set this attribute to the current date and time
    date_added = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return self.name

class Topping(models.Model):
    pizza = models.ForeignKey(Pizza, on_delete=models.CASCADE)
    name = models.TextField()
    #auto_now_add=True - set this attribute to the current date and time
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'Toppings'

    def __str__(self):
        return self.name

class Comment(models.Model):
    pizza = models.ForeignKey(Pizza, on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True,blank=True)


    def __str__(self):
        return self.name

pizzas/forms.py
from django import forms
from .models import Pizza, Topping, Comment
from .models import *


class PizzaForm(forms.ModelForm):
    class Meta:
        model = Pizza
        fields = ['name']
        labels = {'name': ''} 

class ToppingForm(forms.ModelForm):
    class Meta:
        model = Topping
        fields = ['name']
        labels = {'name': ''} 
        widgets = {'text': forms.Textarea(attrs={'cols':80})}

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['name'] 
        labels = {'name': ''} 
      

pizzas/views.py
from django.shortcuts import render, redirect
from .models import Pizza, Topping, Comment
from .forms import CommentForm, PizzaForm, ToppingForm
from .forms import *

# Create your views here.
def index(request):
    ''' The Home Page of the Pizzeria. '''
    return render(request, 'pizzas/index.html')

def pizzas(request):
    ''' Pizza List Page. '''
    pizzas = Pizza.objects.order_by('date_added')

    context = {"pizzas":pizzas}
    return render(request, 'pizzas/pizzas.html', context)

def pizza(request, pizza_id):
    ''' Individual Pizzas. '''
    pizza = Pizza.objects.get(id=pizza_id)
    toppings = pizza.topping_set.order_by('name')
    comments = pizza.comment_set.order_by('date_added')
    context = {'pizza':pizza, 'toppings':toppings, 'comments':comments}
    return render(request, 'pizzas/pizza.html', context)



def new_comment(request, pizza_id):
    pizza = Pizza.objects.get(id=pizza_id)
    
    if request.method != 'POST':
        form = CommentForm()

    else:
        form = CommentForm(data=request.POST)

        if form.is_valid():
            new_comment = form.save(commit=False)
            new_comment.pizza = pizza
            new_comment.save() 

            return redirect('pizzas:pizza', pizza_id=pizza_id)

    context = {'form': form, 'pizza': pizza}

    return render(request, 'pizzas/new_comment.html', context) 

pizzas/templates/pizzas/base.html
<p>
    <body style="background-color: rgb(7, 221, 214);"> </body>

    <font face="Optima" size="100px" color=000000> Papa John's Pizza Palace</font>
    &nbsp&nbsp&nbsp&nbsp
    &nbsp&nbsp&nbsp&nbsp  


    <a href="{% url 'pizzas:index' %}"> HOME________

    <a href="{% url 'pizzas:pizzas' %}"> PIZZAS
    </a>





</p>
{% block content %}

{% endblock content %} 

pizzas/templates/pizzas/images.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Pizza_image</title>
</head>
<body>
    <form method="post" enctype="multipart/form-data">
    {% csrf_token %} 
    {{ form.as_p %}}
    <button type="submit">Upload</button>
    </form>
</body>
</html>

pizzas/templates/pizzas/index.html
{% extends "pizzas/base.html" %} 
{% block title %} 
Home Page | Papa John's Pizzeria
{% endblock %} 
{% block content %}

<p>
    <font face="Optima" size="20px" color="000000 "> Welcome to the home of Waco's world famous pizzeria! </font>
    <img src="static/images/Pizzeria Logo.jpg">
    <br>
    <img src="static/images/Hawaiian_pizza.jpg">
    <img src="static/images/eating.jpg">
    <img src="static/images/pepperoni_pizza.jpg">

</p>

{% endblock content %} 

pizzas/templates/pizzas/new_comment.html
{% extends "pizzas/base.html" %}

{% block content %}

<p><a href="{% url 'pizzas:pizza' pizza.id %}">{{ pizza }}</a></p>
<p>Pleave a review for our pizzas if you have tried them!</p>

<form action="{% url 'pizzas:new_comment' pizza.id %}" method='post'>
    {% csrf_token %} 
    {{ form.as_p }}

    <button name="submit">Submit Comment</button>
</form>


{% endblock content %}

pizzas/templates/pizzas/pizza.html
{% extends "pizzas/base.html" %}
{% block title %}
Pizza List Page | Papa John's Pizzeria
{% endblock %}
{% block content %}

<p>
    <font face="Optima" size="10px" color="00000"> Pizza Information </font>
    <br>
    <img src="static/images/Pizzeria Logo.jpg">
</p>
<p>You are viewing the {{ pizza }}</p>
<p>
    <font face="Optima" size = "6px" color="00000"> Ingredients List </font>
    <br>
    <img src="static/images/Hawaiian_Pizza.jpg">
</p>

{% for topping in toppings %}

{{ topping }}
<br>
{% endfor %}
<br><br>
<p>
    <font face="Optima" size="6px" color="00000"> Comments </font>
</p>
    <ul>
        {% for comment in comments %} 

        <li>
            <p> {{ comment.name|linebreaks }}</p>
        </li>
        {% empty %} 

            <li>No one has left a review for this pizza yet. Please be the first to review our delicious pizzas!</li>
        
        {% endfor %} 
        </li>
    </ul>

    <p>
        <br>
        <a href="{% url 'pizzas:new_comment' pizza.id %}" >Add a new comment</a>
    </p>

{% endblock content %}

pizzas/templates/pizzas/pizzas.html
{% extends "pizzas/base.html" %}
{% block title %}
Pizza List Page | Papa John's Pizzeria
{% endblock %}
{% block content %}

<p>
    <font face="Optima" size="20px" color="000000 "> Select from our delicious list of pizzas! </font>
    <br>
    <img src="static/images/Pizzeria Logo.jpg">
</p>
{% for pizza in pizzas %}
<a href="{% url 'pizzas:pizza' pizza.id %}">
{{ pizza }}
</a>
<br>
{% endfor %}
<br>
<p>
    <img src="static/images/Hawaiian_pizza.jpg">
</p>
{% endblock content %}